#!/bin/bash

echo ""
echo "AbundantOTU+ installer"

CDIR=`pwd`
TMPDIR="Src"
cd $TMPDIR

make clean
make
rm -f -r *.o

cd $CDIR
rm -f -r bin
mkdir bin

mv $TMPDIR/AbundantOTU+ bin/

echo ""
echo "AbundantOTU+ is now installed under bin/"
echo ""

exit 0
