#include "calign.h"
#include <time.h>

main(int argc, char **argv)
{
	calign	*aligneng = new calign;
	aligneng -> set_alnperc(0.03);

	int	tot = 3;
	char	**seq = new char*[tot];
	char	**name = new char*[tot];
	name[0] = new char[100];
	strcpy(name[0],"FIQU8OX06HETT3");
	seq[0] = new char[10000];
	strcpy(seq[0], "ATTAGATACCCTGGTAGTCCTAGCTGTAAACGATGGATACTAGATGTTGTGGACTCTTTGAGTCTGCAGTGTCGTAGCTAACGCGTTAAGTATCCCGCCTGGGAAGTATGCTCGCAAGAGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACACGAAGAACCTTACCAGGACTTGACATAAAGAGAAGTTTTTTGAGAAGAAAACGTGCTACGGCCTCTTATACAGGTGGTG");
	name[1] = new char[100];
	strcpy(name[1],"FIQU8OX06HETT3-1");
	seq[1] = new char[10000];
	strcpy(seq[1], "ATTAGATACCCTGGTAGTCCTAGCTGTAAACGATGGATACTAGATGTTGTGGACTCTTTGAGTCTGCAGTGTCGTAGCTAACGCGTTAAGTATCCCGCCTGGGAAGTATGCTCGCAAGAGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACACGAAGAACCTTACCAGGACTTGACATAAAGAGAAGTTTTTTGAGAAGAAAACGTGCTACGGCCTCTTATACAGGTGGTG");
	//strcpy(seq[1], "ATTAGATACCCAGGTAGTCCTAGCTGTAAACGATGGATACTAGATGTTGTGGACTCTTTGAGTCTGCAGTGTCGTAGCTAACGCGTTAAGTATCCCGCCTGGGAAGTATGCTCGCAAGAGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACACGAAGAACCTTACCAGGACTTGACATAAAGAGAAGTTTTTTGAGAAGAAAAACGTGCTACGGCCTCTTATACAGGTGGTG");
	name[2] = new char[100];
	strcpy(name[2],"FIQU8OX06HETT3-2");
	seq[2] = new char[10000];
	strcpy(seq[2], "ATTAGATACCCCGGTAGTCCTAGCTGTAAACGATGGATACTAGATGTTGTGGGCTCTTTGAGTCTGCAGTGTCGTAGCTAACGCGTTAAGTATCCTGCCTGGGAAGTATGCTCGCAAGAGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACACGAAGAACCTTACCAGGACTTGACATAAAGAGAAGTTTTTTGAGAAGAAAACGTGCTACGGCCTCTTATACAGGTGGTG");

	printf("into getreads\n");
	aligneng -> setverbose();
	aligneng -> getreads(tot, seq, name);
	char *cons = aligneng -> seq2cons();

	int	mis1 = aligneng -> align2charseq(seq[0], seq[1]);
	printf("distance between seq0 and seq1: %d\n", mis1);

	int	mis2 = aligneng -> align2charseq(seq[0], seq[2]);
	printf("distance between seq0 and seq2: %d\n", mis2);

	delete aligneng;
}
